/*
	Alex Klibisz, alexklibisz.github.io, 02/17/2015

	https://projecteuler.net/problem=2
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

var max = 4000000, evenSum = 0;
var fib = 0, n0 = 0, n1 = 1;

while(fib < max) {
	fib = n0 + n1;
	n0 = n1;
	n1 = fib;
	if((fib) % 2 == 0) {
		evenSum += fib;	
	}
}

console.log(evenSum);